logging:
  level:
    org.springframework.security: DEBUG
security:
  sessions: ALWAYS
zuul:
  routes:
    ui:
      url: http://localhost:8081
      sensitive-headers:
    ui2:
      url: http://localhost:8083
      sensitive-headers:  
    ui3:
      url: http://localhost:8084
      sensitive-headers:  
    admin:
      url: http://localhost:8082
      sensitive-headers:
    resource:
      url: http://localhost:9000
      sensitive-headers:
